export type FlagScope = "run" | "year" | "life" | "npc";

export type FlagSpec = {
  id: string;
  producer: string[];
  consumer: string[];
  fallback: string;
  scope: FlagScope;
  debugLabel: string;
  owner: string;
};

/** Formal flags only. A flag with no consumer does not belong here. */
export const FLAG_LEDGER: FlagSpec[] = [
  {
    id: "FLAG_HEARD_ADULT_FUTURE",
    producer: ["EVT_1984_NEWS_01 A", "EVT_1984_NEWS_01 B"],
    consumer: ["heardNews index; 1985 family echo reads MEM_NEWS_01"],
    fallback: "No flag means not heard. Memory choiceId is the fact.",
    scope: "life",
    debugLabel: "聽過將來",
    owner: "news",
  },
  {
    id: "FLAG_PARENT_EXPLAIN",
    producer: ["EVT_1984_NEWS_01 B"],
    consumer: ["EVT_1986_SKILL_05"],
    fallback: "Skill card uses the shorter dad line.",
    scope: "life",
    debugLabel: "阿爸解釋過",
    owner: "news",
  },
  {
    id: "FLAG_HELPED_MOM_01",
    producer: ["EVT_1984_FAMILY_02 A"],
    consumer: ["EVT_1986_MARKET_07"],
    fallback: "Market does not mention the toys.",
    scope: "life",
    debugLabel: "收過玩具",
    owner: "mom",
  },
  {
    id: "FLAG_FIRST_SCHOOL",
    producer: ["EVT_1985_SCHOOL_01"],
    consumer: ["battle memory MEM_FIRST_SCHOOL"],
    fallback: "No school flag if the event was never reached.",
    scope: "life",
    debugLabel: "上過學",
    owner: "school",
  },
  {
    id: "FLAG_TEACHER_SLOW",
    producer: ["EVT_1985_SCHOOL_01 B", "battle bad"],
    consumer: ["EVT_1986_SKILL_05"],
    fallback: "Teacher speaks at the normal pace.",
    scope: "life",
    debugLabel: "老師慢熱",
    owner: "school",
  },
  {
    id: "FLAG_CURIOUS_SCHOOL",
    producer: ["EVT_1985_SCHOOL_01 C"],
    consumer: ["battle approach curious"],
    fallback: "Approach stays safe or social.",
    scope: "run",
    debugLabel: "自己行近",
    owner: "school",
  },
  {
    id: "FLAG_FAMILY_NEWS_SILENCE",
    producer: ["EVT_1985_FAMILY_03"],
    consumer: ["MEM_SILENT_NEWS_01"],
    fallback: "No silence memory if the card was skipped.",
    scope: "life",
    debugLabel: "屋企靜過",
    owner: "family",
  },
  {
    id: "FLAG_TOY_MONOPOLY",
    producer: ["EVT_1985_FRIEND_04 A"],
    consumer: ["EVT_1986_SKILL_05"],
    fallback: "Ah Jit sits at a normal distance.",
    scope: "life",
    debugLabel: "霸住個波",
    owner: "friend",
  },
  {
    id: "FLAG_SHARED_BALL",
    producer: ["EVT_1985_FRIEND_04 B"],
    consumer: ["EVT_1986_SKILL_05"],
    fallback: "No wave from Ah Jit.",
    scope: "life",
    debugLabel: "輪住玩",
    owner: "friend",
  },
  {
    id: "FLAG_AVOID_CONFLICT",
    producer: ["EVT_1985_FRIEND_04 C"],
    consumer: ["EVT_1986_SKILL_05"],
    fallback: "The seat line is not about walking away.",
    scope: "life",
    debugLabel: "行開",
    owner: "friend",
  },
  {
    id: "FLAG_FIRST_INTEREST_CHOICE",
    producer: ["EVT_1986_SKILL_05"],
    consumer: ["MEM_FIRST_INTEREST"],
    fallback: "No interest memory.",
    scope: "life",
    debugLabel: "揀過興趣",
    owner: "skill",
  },
  {
    id: "FLAG_DAD_OVERTIME_MEMORY",
    producer: ["EVT_1986_FAMILY_06"],
    consumer: ["MEM_DAD_WORK", "ending"],
    fallback: "Ending has no dad-work sentence.",
    scope: "life",
    debugLabel: "記得阿爸返工",
    owner: "dad",
  },
  {
    id: "FLAG_DAD_WILL_COMPENSATE",
    producer: ["EVT_1986_FAMILY_06 A"],
    consumer: ["EVT_1986_ECHO_08"],
    fallback: "Echo does not mention a later promise.",
    scope: "life",
    debugLabel: "話會補返",
    owner: "dad",
  },
  {
    id: "FLAG_MARKET_KINDNESS",
    producer: ["EVT_1986_MARKET_07 A", "EVT_1986_MARKET_07 C"],
    consumer: ["MEM_MARKET_01"],
    fallback: "No market memory.",
    scope: "life",
    debugLabel: "街市人情",
    owner: "market",
  },
  {
    id: "FLAG_FAVOUR_QUESTION",
    producer: ["EVT_1986_MARKET_07 B"],
    consumer: ["EVT_1986_ECHO_08"],
    fallback: "Echo does not mention the unpaid vegetable.",
    scope: "life",
    debugLabel: "問人情",
    owner: "market",
  },
  {
    id: "FLAG_FIRST_INDEPENDENCE",
    producer: ["EVT_1986_ECHO_08"],
    consumer: ["MEM_FIRST_INDEPENDENCE", "ending"],
    fallback: "Skip memory covers an explicit refusal.",
    scope: "life",
    debugLabel: "到過邨口",
    owner: "echo",
  },
  {
    id: "FLAG_RETRY_SCHOOL",
    producer: ["battle fail", "battle bad"],
    consumer: ["MEM_FIRST_SCHOOL"],
    fallback: "Win and perfect do not set a retry.",
    scope: "life",
    debugLabel: "第一日未入到",
    owner: "school",
  },
  {
    id: "FLAG_GATE_DECLINED",
    producer: ["explore stay home"],
    consumer: ["openNext skips EVT_1986_ECHO_08"],
    fallback: "The offer repeats until the gate is met.",
    scope: "run",
    debugLabel: "留喺屋企",
    owner: "echo",
  },
  {
    id: "FLAG_REPAIR_TALK",
    producer: ["repair talk"],
    consumer: ["ending"],
    fallback: "Ending does not mention the confession.",
    scope: "life",
    debugLabel: "同阿媽講",
    owner: "repair",
  },
  {
    id: "FLAG_REPAIR_SILENT",
    producer: ["repair silent"],
    consumer: ["ending"],
    fallback: "Ending does not mention the swallowed night.",
    scope: "life",
    debugLabel: "冇講",
    owner: "repair",
  },
];

export const RETIRED_FLAGS = ["FLAG_GATE_RISK", "FLAG_SELF_COMFORT", "NPC_DAD_OVERTIME_COUNT"] as const;
